### ISSUE TITLE
your own fake64 status and future

### ISSUE THREAD

**Issue by mckaygerhard** [cxd4/Fake64#1]
hi, i recently see some commits in that repository seems you wants something to work here!

1. What is the status of the project?
2. now have a hard depend on opengl ?
3. If need Opengl will need a very modern or i can play at my minilaptop?

NOTE: I think that being a mathematical person you will have in mind that it is illogical that a machine of more than 2GHz is needed to play one of only 133MHz, i mean...

Thanks in advance i do not have great skills but i try to collaborate if most answers are positive

**Comment by cxd4** [comment]
No to all three questions.

Fake64 is an old project from 2003; it does not require a 2-GHz personal computer to play.
